# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78457800eeb3215651434f7249b0cb73d3d6a06f3f441a4e52e4779e9f8ec09395c75c2a45b01c0f908fa03d760ef8031a701df2c6def27f378a7c5d8cc0b3c1

test:
  secret_key_base: 989477108ff8dc6cf9517f79f0e7b4a80f67919397438bf96c0dabd49ee10966c1bf91f9a678749fbddc44d332b8d511a7ea053d12ab2482c1e1165bfc769603

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
